version: "3.3"

services:
  mysql:
    container_name: ecalazaes-mysql
    restart: always
    image: mysql:8.0
    networks:
      - ecalazaesnetwork
    ports:
      - "3307:3306"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: ecalazaes_db
      MYSQL_USER: ecalazaes_user
      MYSQL_PASSWORD: senha

  rabbit:
    container_name: ecalazaes-rabbit
    restart: always
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./volumes/rabbit:/data
    networks:
      - ecalazaesnetwork

networks:
  ecalazaesnetwork:
    driver: bridge